name: Build Library

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn
      - name: Run lint
        run: |
          yarn lint
      - name: Run the tests and generate coverage report
        run: |
          yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
